name: first Check

on: [push, pull_request]

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 
        
      - name: Step one - Print Environment Variables (Linux)
        run: env | sort

  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Step two - Print Environment Variables (Windows)
        run: "Get-ChildItem Env: | Sort-Object Name"
